const path=require('path'); const {chromium}=require('/opt/npm-tools/node_modules/playwright'); const fs=require('fs');
const d3src = fs.readFileSync('node_modules/d3/dist/d3.min.js','utf8'); const tsrc = fs.readFileSync('node_modules/topojson-client/dist/topojson-client.min.js','utf8');
(async()=>{ const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-sandbox','--proxy-server=direct://']});
 const ctx=await b.newContext({viewport:{width:1440,height:900}}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>{ if(m.type()==='error'&&!/ERR_FAILED/.test(m.text())) errs.push(m.text()); });
 await p.route('**/*', r=>{ const u=r.request().url(); if(u.includes('d3.min.js')) return r.fulfill({contentType:'application/javascript',body:d3src}); if(u.includes('topojson-client')) return r.fulfill({contentType:'application/javascript',body:tsrc}); if(u.startsWith('file:')) return r.continue(); return r.abort(); });
 await p.goto('file://'+path.resolve('test.html')); await p.waitForTimeout(1500);
 const t=async(label,fn,wait=1800)=>{ await fn(); await p.waitForTimeout(wait); const r=await p.evaluate(()=>({h2:document.querySelector('#infobody h2')?.textContent, wide:document.getElementById('map-section').classList.contains('wide'), on:[...document.querySelectorAll('#focus button.on')].map(b=>b.textContent), xv:[...document.querySelectorAll('.xtoggle.onmap [aria-pressed=true]')].map(b=>b.dataset.xv).join(), k:window.__atlasTest.T().k.toFixed(2), bd:(document.querySelector('.mborder')?.getAttribute('d')||'').length})); console.log(label.padEnd(26), JSON.stringify(r)); };
 await t('start', async()=>{});
 await t('chip Makkah (zoom in)', ()=>p.click('#focus button:has-text("Ḥaram of Makkah")'), 3000);
 const ft=Date.now(); await p.mouse.move(500,450); await p.mouse.down(); await p.mouse.move(560,470,{steps:6}); await p.mouse.up(); await p.waitForTimeout(800); console.log('drag at makkah ms', Date.now()-ft);
 await t('chip Greater Caliphate', ()=>p.click('#focus button:has-text("Greater Caliphate")'), 2500);
 await t('chip al-Sham', ()=>p.click('#focus button:has-text("al-Shām")'), 2500);
 await t('switch To Iraq', ()=>p.click('.xtoggle.onmap [data-xv="west"]'));
 await t('switch + Greater', ()=>p.click('.xtoggle.onmap [data-xv="gme"]'), 2500);
 await t('switch Complete', ()=>p.click('.xtoggle.onmap [data-xv="full"]'), 2500);
 await t('hash outline-iraq', ()=>p.evaluate(()=>location.hash='outline-iraq'), 2500);
 await t('hash outline-greater', ()=>p.evaluate(()=>location.hash='outline-greater'), 2500);
 await t('preset overview', ()=>p.click('#presets button[data-p="overview"]'), 2500);
 await t('search khartoum', async()=>{ await p.fill('#placeq','khartoum'); await p.waitForTimeout(300); await p.keyboard.press('Enter'); }, 2500);
 console.log('errs', errs);
 await b.close(); })();
