/* ================= v4: new geometry ================= */
const GEN = __GENERATED__;
const UPPER = GEN.UPPER, IRAQ = GEN.IRAQ, MISR_CORE = GEN.MISR_CORE, DELTA = GEN.DELTA;
// Yāqūt's reckoning of Miṣr: length from the two trees between Rafaḥ and al-ʿArīsh to Aswān; width from Barqah to Aylah
const MISR_OUTER = [
  {c:"sea", p:[[34.25,31.29],[33.5,31.9],[32.0,33.3],[20.1,33.3]]},
  {c:"uncertain", p:[[20.1,33.3],[20.1,23.95]]},
  {c:"uncertain", p:[[20.1,23.95],[36.0,23.95]]},
  {c:"sea", p:[[36.0,23.95],[35.2,26.2],[34.7,27.7],[34.72,28.5],[35.0,29.52]]},
  {c:"uncertain", p:[[35.0,29.52],[34.25,31.29]]}
];
const NAJD = [
  {c:"uncertain", p:[[41.3,27.9],[42.7,28.5],[44.4,27.8],[45.9,27.0],[47.2,26.2],[47.9,25.0],[47.7,23.4],[46.8,22.0],[45.3,21.3],[43.6,21.8],[42.3,22.6],[41.6,23.6],[41.55,25.4],[41.3,27.9]]}
];
const BAHRAYN = [
  {c:"uncertain", p:[[47.6,29.3],[47.8,28.2],[48.3,27.2],[48.9,26.3],[49.4,25.3],[50.0,24.6],[50.9,24.2]]},
  {c:"sea", p:[[50.9,24.2],[52.0,24.3],[52.0,26.4],[50.6,28.0],[49.2,29.7],[47.6,29.3]]}
];
const TIHAMAH = [
  {c:"uncertain", p:[[43.45,12.7],[43.5,13.7],[43.45,14.8],[43.15,15.8],[42.95,16.7],[42.6,17.4],[42.1,18.2],[41.6,19.1],[41.0,20.0],[40.6,20.8],[40.1,21.4],[39.75,22.2],[39.4,23.2],[38.7,24.2]]},
  {c:"sea", p:[[38.7,24.2],[37.4,24.2],[37.9,22.0],[39.0,19.5],[40.8,16.5],[42.0,13.8],[43.0,12.3],[43.45,12.7]]}
];
const RUM = [
  {c:"uncertain", p:[[34.6,36.62],[34.55,36.9],[34.9,37.3],[35.8,37.55],[36.95,37.75],[37.6,38.15],[38.3,38.45],[38.6,39.4],[38.6,41.2]]},
  {c:"sea", p:[[38.6,41.2],[38.6,42.6],[24.5,42.6],[24.5,35.9],[34.6,35.9],[34.6,36.62]]}
];
const ARAB_IDS = ["682","887","512","784","634","048","414"];
// al-Aḥqāf: three reports in al-Baghawī on 46:21; sizes are illustrative
const AHQAF = [
  {id:"qatadah", n:"Qatādah", c:[49.60,14.76], km:55, s:"al-Shiḥr, on the sea"},
  {id:"muqatil", n:"Muqātil", c:[52.20,16.20], km:55, s:"Mahrah, in Ḥaḍramawt"},
  {id:"ibnabbas", n:"Ibn ʿAbbās", c:[53.60,17.00], km:55, s:"between ʿUmān and Mahrah"}
];
const MARIB = [45.33,15.43];
const AKSUM = [38.72,14.13];
const SABA_ROUTE = [[45.33,15.43],[44.13,17.49],[43.1,18.7],[42.25,19.97]];
// end-times places (hadith); positions approximate
const ESCHAT = [
  {id:"ghutah", n:"al-Ghūṭah", s:"near Damascus", ll:[36.37,33.50], a:"l", k:1.6},
  {id:"dabiq", n:"Dābiq", s:"the village; coordinates after Wikipedia", ll:[37.268,36.537], a:"r", k:1.2},
  {id:"amaq", n:"al-Aʿmāq", s:"plain of Antioch", ll:[36.35,36.35], a:"l", k:1.6},
  {id:"ludd", n:"Bāb Ludd", s:"gate of Lydda", ll:[34.895,31.951], a:"l", k:2.4},
  {id:"qustantiniyyah", n:"Qusṭanṭīniyyah", s:"Caesar's city · Istanbul", ll:[28.98,41.01], a:"r", k:0.9}
];
const QIBLA = {
  madinah:[39.6111,24.4672], makkah:[39.8262,21.4225], aqsa:[35.2355,31.7779]
};
/* one outline around every best land: my synthesis, generated by caliph_gen.js from the region outlines and Natural Earth countries */
const CALIPH = JSON.parse(document.getElementById('caliph').textContent);   /* kept as data, not code: the browser reads it faster */
